### ISSUE TITLE
Assistance Required with ChromaDB Plugin Installation on M3 Max Devices, Including macOS Error

### ISSUE THREAD

**Issue by kruzea22** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#122]
macOS Platform Issue:

The process similarly begins with document loading and processing.
A critical error occurs during embedding creation, related to a failure in loading the model state dict, followed by an OSError suggesting an issue with git-lfs not being installed or properly set up.
The error messages suggest migrating data to the new Chroma architecture if existing data needs to be preserved, or updating the Chroma client construction method for new installations. It references documentation and support channels for further guidance.

Given the technical nature of these issues and my limited experience, I find myself in need of your expert guidance to navigate these problems. Specifically, I am seeking advice on:

Addressing the deprecated configuration error for a new installation on Windows 11.
Resolving the OSError related to git-lfs on macOS for smooth operation of the ChromaDB Plugin.
Ensuring compatibility and smooth operation of the ChromaDB Plugin on an M3 Max device, if any specific considerations are required.
Any additional resources or support channels you recommend for troubleshooting and learning more about leveraging your tool to its fullest potential.

The specific error encountered on the MAC platform is as follows:

No files detected in the 'Images_for_DB' directory.
database_interactions.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 3
document_processor.py: Chunks between 1 and 100 characters: 0
document_processor.py: Chunks between 101 and 200 characters: 3
database_interactions.py: Creating embeddings.
sentence_transformers.SentenceTransformer - /Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py:66 - __init__
Traceback (most recent call last):
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/Users/geiwotmk/lib/python3.9/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/geiwotmk/lib/python3.9/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geiwotmk/Downloads/src/gui_tabs_databases.py", line 16, in run
    create_vector_db.run()
  File "/Users/geiwotmk/Downloads/src/database_interactions.py", line 50, in run
    embeddings = self.get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File "/Users/geiwotmk/Downloads/src/database_interactions.py", line 103, in get_embeddings
    return HuggingFaceEmbeddings(
  File "/Users/geiwotmk/lib/python3.9/site-packages/langchain/embeddings/huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3381, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 524, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
/Users/geiwotmk/bin/python3 -m pip install --upgrade pip
database_interactions.py: Loading documents.
document_processor.py: Number of workers assigned: 3
/Users/geiwotmk/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/geiwotmk/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/geiwotmk/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
document_processor.py: Number of NON-IMAGE files loaded: 1
document_processor.py: Number of NON-IMAGE files loaded: 2
document_processor.py: Number of NON-IMAGE files loaded: 3
document_processor.py: Loading images, if any.
/Users/geiwotmk/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
No files detected in the 'Images_for_DB' directory.
database_interactions.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 3
document_processor.py: Chunks between 1 and 100 characters: 0
document_processor.py: Chunks between 101 and 200 characters: 3
database_interactions.py: Creating embeddings.
sentence_transformers.SentenceTransformer - /Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py:66 - __init__
Traceback (most recent call last):
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 519, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/Users/geiwotmk/lib/python3.9/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/geiwotmk/lib/python3.9/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/geiwotmk/Downloads/src/gui_tabs_databases.py", line 16, in run
    create_vector_db.run()
  File "/Users/geiwotmk/Downloads/src/database_interactions.py", line 50, in run
    embeddings = self.get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File "/Users/geiwotmk/Downloads/src/database_interactions.py", line 103, in get_embeddings
    return HuggingFaceEmbeddings(
  File "/Users/geiwotmk/lib/python3.9/site-packages/langchain/embeddings/huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "/Users/geiwotmk/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3381, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Users/geiwotmk/lib/python3.9/site-packages/transformers/modeling_utils.py", line 524, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
(geiwotmk) geiwotmk@geiwotdeMBP src % /Users/geiwotmk/bin/python3 -m pip install --upgrade pip
Requirement already satisfied: pip in /Users/geiwotmk/lib/python3.9/site-packages (23.3.2)
(geiwotmk) geiwotmk@geiwotdeMBP src % git lfs install
Git LFS initialized.
(geiwotmk) geiwotmk@geiwotdeMBP src % git lfs pull
Not in a Git repository.

**Comment by BBC-Esq** [comment]
Install git lfs, it's different than git.
