### ISSUE TITLE
Documentation / code fix  required related to git-lfs requirement

### ISSUE THREAD

**Issue by vmirea** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#16]
I'm not sure if it's a bug in the code or just the steps need to be documented
After downloading the embeded model hkunlp--instructor-xl I got an error.
I needed to go manually in the folder and run "git lfs install" + "git lfs pull"
Every time a new embeded model is selected do we need to run manually the commands above? If yes you might need to add that to documentation.

DEBUG EMBEDDING_MODEL_NAME=/media/vmirea/NTFS_8TB/projects/llama/llama-recipes/llm_qlora/examples/ChromaDB-Plugin-for-LM-Studio/Embedding_Models/hkunlp--instructor-xl
load INSTRUCTOR_Transformer
Traceback (most recent call last):
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 484, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/External_disk/ubuntu/pytorch/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/External_disk/ubuntu/pytorch/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/vmirea/NTFS_8TB/projects/llama/llama-recipes/llm_qlora/examples/ChromaDB-Plugin-for-LM-Studio/gui.py", line 32, in run
    create_database.main()
  File "/media/vmirea/NTFS_8TB/projects/llama/llama-recipes/llm_qlora/examples/ChromaDB-Plugin-for-LM-Studio/create_database.py", line 35, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, COMPUTE_DEVICE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vmirea/NTFS_8TB/projects/llama/llama-recipes/llm_qlora/examples/ChromaDB-Plugin-for-LM-Studio/create_database.py", line 60, in get_embeddings
    return HuggingFaceInstructEmbeddings(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 148, in __init__
    self.client = INSTRUCTOR(
                  ^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    if os.path.exists(os.path.join(model_path, 'modules.json')):    #Load as SentenceTransformer model
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/InstructorEmbedding/instructor.py", line 474, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/InstructorEmbedding/instructor.py", line 306, in load
    return INSTRUCTOR_Transformer(model_name_or_path=input_path, **config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/InstructorEmbedding/instructor.py", line 240, in __init__
    self._load_model(self.model_name_or_path, config, cache_dir, **model_args)
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 47, in _load_model
    self._load_t5_model(model_name_or_path, config, cache_dir)
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/sentence_transformers/models/Transformer.py", line 55, in _load_t5_model
    self.auto_model = T5EncoderModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3019, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vmirea/miniconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 489, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.

**Comment by BBC-Esq** [comment]
Try deleting the folder holding the embedding model altogether, then make sure to have Git
 LFS installed, then try and download the model with my program.
 If it still gives an error, let me know and it's a true bug.
