### ISSUE TITLE
Can't run `python gui.py`: AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'

### ISSUE THREAD

**Issue by D-Vaillant** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#25]
On a Mac, Python 3.10. Got everything working up until trying to run the dang thing:
```
Traceback (most recent call last):
  File "/Users/david/src/llms/APIER/ChromaDB-Plugin-for-LM-Studio-2.6/src/gui.py", line 13, in <module>
    import create_database
  File "/Users/david/src/llms/APIER/ChromaDB-Plugin-for-LM-Studio-2.6/src/create_database.py", line 19, in <module>
    torch.cuda.reset_peak_memory_stats()
  File "/Users/david/src/llms/APIER/ChromaDB-Plugin-for-LM-Studio-2.6/src/venv/lib/python3.10/site-packages/torch/cuda/memory.py", line 307, in reset_peak_memory_stats
    return torch._C._cuda_resetPeakMemoryStats(device)
AttributeError: module 'torch._C' has no attribute '_cuda_resetPeakMemoryStats'
```

**Comment by BBC-Esq** [comment]
Go into ```create_database.py``` and specifically ```line 19``` and put a pound sign before it to comment that line out, and then let me know if that solves the issue.  So line 19 should read as follows: ```# torch.cuda.reset_peak_memory_stats()```.  This line was for debugging purposes and I'll make sure and comment it out when I make a release in the future.
