### ISSUE TITLE
Cannot Connect to LM Studio

### ISSUE THREAD

**Issue by ameen-roayan** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#31]
Heya, 

i am getting errors and scratching my head as to what is causing it.

Traceback (most recent call last):
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\vx_10\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002091F08E710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002091F08E710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\openai\api_requestor.py", line 596, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\requests\sessions.py", line 587, in request    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002091F08E710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\gui_threads.py", line 19, in run
    response = server_connector.ask_local_chatgpt(self.user_question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\server_connector.py", line 164, in ask_local_chatgpt
    response_json = connect_to_local_chatgpt(augmented_query)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\server_connector.py", line 80, in connect_to_local_chatgpt
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\openai\api_requestor.py", line 288, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "F:\AI\Lm Studio\ChromaDB-Plugin-for-LM-Studio-main\Lib\site-packages\openai\api_requestor.py", line 609, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002091F08E710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by BBC-Esq** [comment]
Sometimes for some reason the server stops receiving the connection even
 though you've clicked start server. So I recommend clicking stop server and then
 start server again. That should fix the issue.   That's an issue with LM Studio, not my program.

**Comment by BBC-Esq** [comment]
Bug report dis-confirmed by redownloading model.
