### ISSUE TITLE
git-lfs not found?

### ISSUE THREAD

**Issue by rm-rf-etc** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#32]
System: 2020 MacBook Air, M1, Ventura 13.4 (22F66)

This is the terminal output I get from running `gui.py` and trying to create the vector database.

```
qt.qpa.fonts: Populating font family aliases took 113 ms. Replace uses of missing font family "Segoe UI Historic" with one that exists to avoid this cost.
2023-11-27 01:49:27.047 python[53547:20772856] +[CATransaction synchronize] called within transaction
Selected directory: /Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/Embedding_Models/sentence-transformers--multi-qa-mpnet-base-cos-v1
create_database.py: Loading documents.
document_processor.py: Number of workers assigned: 8
document_processor.py: Number of files loaded: 38
document_processor.py: Number of files loaded: 76
document_processor.py: Number of files loaded: 112
document_processor.py: Number of files loaded: 150
document_processor.py: Number of files loaded: 188
document_processor.py: Number of files loaded: 226
document_processor.py: Number of files loaded: 264
document_processor.py: Number of files loaded: 302
create_database.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 152635
document_processor.py: Chunks between 1 and 100 characters: 3940
document_processor.py: Chunks between 101 and 200 characters: 2772
document_processor.py: Chunks between 201 and 300 characters: 6829
document_processor.py: Chunks between 301 and 400 characters: 17607
document_processor.py: Chunks between 401 and 500 characters: 24515
document_processor.py: Chunks between 501 and 600 characters: 96972
create_database.py: Creating embeddings.
Traceback (most recent call last):
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/transformers/modeling_utils.py", line 484, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/gui_threads.py", line 9, in run
    create_database.main()
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/create_database.py", line 65, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/create_database.py", line 131, in get_embeddings
    return HuggingFaceEmbeddings(
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 64, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3170, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/Users/rob/ChromaDB-Plugin-for-LM-Studio-2.7/src/lib/python3.10/site-packages/transformers/modeling_utils.py", line 489, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
2023-11-27 02:01:10.510 python[53547:20772856] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (1.03 secs).
```

In the same directory, I ran the command that the error tells me to run: `git lfs install`. This returns with the message, `Git LFS initialized.`

**Comment by BBC-Esq** [comment]
I think the error message stems from not properly downloading the embedding model and/or waiting until it's completely downloaded.  The files may have been partially downloaded or corrupted somehow.  Try deleting the folder holding the embedding model and any of its associated files.  Then re-download.  Make sure and wait until the command prompt says that it's completed downloading and unpacked, which will be indicated by a print statement that it's ready to use in the command prompt.

Then follow the instructions, select docs...select embedding model folder (NOT THE EMBEDDING_MODELS FOLDER), and create the database.

**Comment by BBC-Esq** [comment]
Resolved by deleting folder and re-downloading.
