### ISSUE TITLE
Issue embedding markdown files

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#98]
Issue embedding markdown files

Traceback (most recent call last):
  File "/Users/click/ChromaLM331/src/gui_threads.py", line 7, in run
    create_database.main()
  File "/Users/click/ChromaLM331/src/create_database.py", line 46, in main
    documents = load_documents(SOURCE_DIRECTORY) # invoke document_processor.py; returns a list of document objects
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/ChromaLM331/src/document_processor.py", line 120, in load_documents
    contents, _ = future.result()
                  ^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'markdown'

**Comment by BBC-Esq** [comment]
Try ```pip install Markdown``` and let me know.  I might not have added it to the ```requirements.txt``` file...
